name: Consulta de Cliente

on:
  workflow_dispatch:

jobs:
  notificar_consulta:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje de consulta
        run: echo "ğŸ” Se ha consultado la informaciÃ³n de un cliente."
