name: Modificaci贸n del C贸digo

on:
  push:
    branches:
      - main

jobs:
  notificar_modificacion_codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Detectar cambios
        run: echo " Se ha modificado el c贸digo de la aplicaci贸n."
